### ISSUE TITLE
Quickmode broken after login and logout

### ISSUE THREAD

**Issue by hailey123** [quentinlautischer/NoteDown#9]
Need to investigate more how to reproduce.  I logged in and went in a couple of folders, typed a little but didn't cloud push.  Then logged out and clicked quick mode and got this error.
<img width="1000" alt="screen shot 2017-03-31 at 7 03 18 pm" src="https://cloud.githubusercontent.com/assets/9269522/24573753/f829327c-1644-11e7-98ac-61c2674bf6ef.png">

**Comment by quentinlautischer** [comment]
Should be fixed
